### PR TITLE
Power Menu animations [1/2]

### PR DESCRIPTION
**Pull request by mrhainavn**
these optional and add an option for the top/button/default animations Power Menu:
- Slide in from the bottom
- Slide in from the top
- Set to the default AOSP animation

### CODE REVIEW

**Comment by mrhainavn** [comment]
@mydongistiny

**Comment by mydongistiny** [comment]
Even though I think he's a huge douche Alex Cruz wrote this code. Where is the authorship?

**Comment by mrhainavn** [comment]
@mydongistiny 
yes, i think him and team DU is author.
https://github.com/DirtyUnicorns/android_frameworks_base/commit/f7c3920228de49afa6b609d48d9fb0a62ec1a177
https://github.com/DirtyUnicorns/android_packages_apps_DU-Tweaks/commit/02a9ab66f652170bc6e0c75207acd01d0628a1aa
please merge them, this is featutes very nice. Thanks man.

**Comment by mydongistiny** [comment]
This feature as it is in the pull requests won't work with this ROM.

**Pull request closed without merging**
